routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'UserController@index');

Route::resource('users', 'UserController');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'lastname', 'email', 'phone', 'address'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Validator;
use Illuminate\Http\Request;
use App\User;

class UserController extends Controller
{
    const ROW_BY_PAGE = 10;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $query = User::query();
        $items = $query->paginate(self::ROW_BY_PAGE);

        return view('user.index', compact('items'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $item = new User;
        $method = 'POST';
        $action = route('users.store');

        return view('user.createOrEdit', compact('item', 'action', 'method'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
           'name' => 'required|string',
           'email' => 'required|string|email|max:100|unique:users,email'
        ]);

        if ($validator->fails()) {
           return back()->withErrors($validator)->withInput();
        }

        $item = User::create($request->all());

        return redirect('/')->with('success', 'Usuario creado exitosamente');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      $item = User::find($id);
      $method = 'PUT';
      $action = route('users.update', $id);

      return view('user.createOrEdit', compact('item', 'action', 'method'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), [
           'name' => 'required|string',
           'email' => 'required|string|email|max:100|unique:users,email,'.$id.',id'
        ]);

        if ($validator->fails()) {
           return back()->withErrors($validator)->withInput();
        }

        $item = User::find($id);

        $item->update($request->all());

        return redirect('/')->with('success', 'Usuario actualizado exitosamente');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $item = User::find($id);
        $item->delete();

        return redirect('/')->with('success', 'Usuario eliminado exitosamente');
    }
}

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>CRUD|usuarios</title>
    <link href="{{ asset('css/app.min.css') }}" rel="stylesheet">
</head>
<body>
  <div class="content mt-3">
          <div class="col-sm-12">
              <div class="response"></div>
                @if (Session::has('success'))
                  <div class="alert alert-success">
                    {!! Session::get('success') !!}
                  </div>
                @endif
                @if (Session::has('error'))
                  <div class="alert alert-danger">
                    {!! Session::get('error') !!}
                  </div>
                @endif

              @yield('content')
          </div>
        </div>
</body>
</html>

resources/views/user/createOrEdit.blade.php
@extends('layouts.app')

@section('content')
  <div class="card">
    <div class="card-body">
      <h1>
      @if(isset($item->id))
        Actualizar usuario
      @else
        Crear usuario
      @endif
      </h1>

      @if ($errors->any())
          <div class="alert alert-danger">
              <ul>
                  @foreach ($errors->all() as $error)
                      <li>{{ $error }}</li>
                  @endforeach
              </ul>
          </div>
      @endif

      <form action="{{$action}}" method="POST">
        {{ method_field($method) }}
        @csrf
        <div class="row">
            <div class="col-xs-12 col-md-6 col-sm-6 col-lg-6">
              <div class="form-group">
                  <label for="title" class="control-label">
                    Nombre
                  </label>
                  <input id="name" name="name" type="text"
                    class="form-control" value="{{ old('name', $item->name) }}"
                    required>
              </div>
            </div>
            <div class="col-xs-12 col-md-6 col-sm-6 col-lg-6">
              <div class="form-group">
                  <label for="title" class="control-label">
                    Apellido
                  </label>
                  <input id="lastname" name="lastname" type="text"
                    class="form-control" value="{{ old('lastname', $item->lastname) }}"
                    required>
              </div>
            </div>
            <div class="col-xs-12 col-md-6 col-sm-6 col-lg-6">
              <div class="form-group">
                  <label for="title" class="control-label">
                    email
                  </label>
                  <input id="email" name="email" type="email"
                    class="form-control" value="{{ old('email', $item->email) }}"
                    required>
              </div>
            </div>
            <div class="col-xs-12 col-md-6 col-sm-6 col-lg-6">
              <div class="form-group">
                  <label for="title" class="control-label">
                    Teléfono
                  </label>
                  <input id="phone" name="phone" type="text"
                    class="form-control" value="{{ old('phone', $item->phone) }}">
              </div>
            </div>
            <div class="col-xs-12 col-md-6 col-sm-6 col-lg-6">
              <div class="form-group">
                  <label for="title" class="control-label">
                    Dirección
                  </label>
                  <input id="address" name="address" type="text"
                    class="form-control" value="{{ old('address', $item->address) }}">
              </div>
            </div>
        </div>
        <div class="form-group">
          <button type="submit" class="btn btn-primary">
              @if(isset($item->id))
                Actualizar
              @else
                Crear
              @endif
          </button>
          <a href="{{ route('users.index') }}" class="btn btn-secondary">
              Volver
          </a>
        </div>
      </form>
    </div>
  </div>
@endsection

resources/views/user/index.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
  <div class="col-12">
    <div class="card">
        <div class="card-body">
            <a href="{{ route('users.create') }}" class="btn btn-primary pull-right">
              Agregar usuario
            </a>
            <br><br>
            @if(isset($items))
            <div class="table-responsive">
              <table class="table">
                  <thead>
                    <tr>
                      <th scope="col">Nombre</th>
                      <th scope="col">Apellido</th>
                      <th scope="col">Email</th>
                      <th scope="col">Teléfono</th>
                      <th scope="col">Dirección</th>
                      <th scope="col">Acciones</th>
                    </tr>
                  </thead>
                  <tbody>
                    @if($items->count())
                      @foreach ($items as $item)
                        <tr>
                          <td>{{ $item->name }}</td>
                          <td>{{ $item->lastname }}</td>
                          <td>{{ $item->email }}</td>
                          <td>{{ $item->phone }}</td>
                          <td>{{ $item->address }}</td>
                          <td>
                            <a href="{{ route('users.edit', $item->id) }}" class="btn btn-primary btn-sm">
                              Editar
                            </a>
                            <form method="POST" action="{{route('users.destroy', $item->id)}}">
                                @csrf
                                <input type="hidden" name="_method" value="DELETE">
                                <button class="btn btn-danger btn-sm" type="submit">
                                  Eliminar
                                </button>
                            </form>
                          </td>
                        </tr>
                      @endforeach
                    @else
                        <tr class="text-center"><td colspan="6">Sin registros</td></tr>
                    @endif
                  </tbody>
              </table>
            </div>
              <div style="float: right">
              {{ $items->appends(request()->except(['page','_token'])) }}
              </div>
            @endif
        </div>
    </div>
</div>
</div>
@endsection